const mammals = [

    { 'id': 'CS11839', 'caption': 'Tiger (Cub - X-Mark)', 'filename': 'CSIMG_1839_Tiger_XMarkCub_UmredKarhandla.png', 'location': 'Umred Karhandla', 'year': '2025', 'desc': '' },
    { 'id': 'CS11884', 'caption': 'Tiger (Cub - X-Mark)', 'filename': 'CSIMG_1884_Tiger_XMarkCub_UmredKarhandla.png', 'location': 'Umred Karhandla', 'year': '2025', 'desc': '' },
    { 'id': 'CS11919', 'caption': 'Tiger (Cub - X-Mark)', 'filename': 'CSIMG_1919_Tiger_XMarkCub_UmredKarhandla.png', 'location': 'Umred Karhandla', 'year': '2025', 'desc': '' },
    { 'id': 'CS12051', 'caption': 'Tiger (Cub - X-Mark)', 'filename': 'CSIMG_2051_Tiger_XMarkCub_UmredKarhandla.png', 'location': 'Umred Karhandla', 'year': '2025', 'desc': '' },
    { 'id': 'CS12123', 'caption': 'Tiger (Cub - X-Mark)', 'filename': 'CSIMG_2123_Tiger_XMarkCub_UmredKarhandla.png', 'location': 'Umred Karhandla', 'year': '2025', 'desc': '' },
    { 'id': 'CS12154', 'caption': 'Tiger (Cub - X-Mark)', 'filename': 'CSIMG_2154_Tiger_XMarkCub_UmredKarhandla.jpg', 'location': 'Umred Karhandla', 'year': '2025', 'desc': '' },
    { 'id': 'CS12154-1', 'caption': 'Tiger  (Cub - X-Mark)', 'filename': 'CSIMG_2154_Tiger_XMarkCub_UmredKarhandla.png', 'location': 'Umred Karhandla', 'year': '2025', 'desc': '' },
    { 'id': 'CS12345', 'caption': 'Tiger (Cub - T26)', 'filename': 'CSIMG_2345_Tiger_T26Cub_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12376', 'caption': 'Tiger (T26)', 'filename': 'CSIMG_2376_Tiger_T26_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12451', 'caption': 'Tiger (T26)', 'filename': 'CSIMG_2451_Tiger_T26_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12523', 'caption': 'Tiger (T26)', 'filename': 'CSIMG_2523_Tiger_T26_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12550', 'caption': 'Tiger (T26)', 'filename': 'CSIMG_2550_Tiger_T26_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12558', 'caption': 'Tiger (T26)', 'filename': 'CSIMG_2558_Tiger_T26_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12575', 'caption': 'Tiger (T26)', 'filename': 'CSIMG_2575_Tiger_T26_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12585', 'caption': 'Tiger (T26)', 'filename': 'CSIMG_2585_Tiger_T26_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12603', 'caption': 'Tiger (T26)', 'filename': 'CSIMG_2603_Tiger_T26_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12638', 'caption': 'Tiger (T26)', 'filename': 'CSIMG_2638_Tiger_T26_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12664', 'caption': 'Tiger (Cub - T26)', 'filename': 'CSIMG_2664_Tiger_T26Cub_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12684', 'caption': 'Tiger (Cub - T26)', 'filename': 'CSIMG_2684_Tiger_T26Cub_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12693', 'caption': 'Tiger (Cub - T26)', 'filename': 'CSIMG_2693_Tiger_T26Cub_UmredPauni.png', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS12715', 'caption': 'Nilgai', 'filename': 'CSIMG_2715_Nilgai_UmredPauni.jpg', 'location': 'Umred Pauni', 'year': '2025', 'desc': '' },
    { 'id': 'CS13021', 'caption': 'Sambar Deer', 'filename': 'CSIMG_3021_SmabarDeer.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13064', 'caption': 'Spotted Deer', 'filename': 'CSIMG_3064_SpottedDeer.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13390', 'caption': 'Indian Golden Jackal', 'filename': 'CSIMG_3390_IndianGoldenJackal.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13402', 'caption': 'Indian Golden Jackal', 'filename': 'CSIMG_3402_IndianGoldenJackal.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13415', 'caption': 'Indian Golden Jackal', 'filename': 'CSIMG_3415_IndianGoldenJackal.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13429', 'caption': 'Indian Golden Jackal', 'filename': 'CSIMG_3429_IndianGoldenJackal.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13454', 'caption': 'Indian Golden Jackal', 'filename': 'CSIMG_3454_IndianGoldenJackal.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13463', 'caption': 'Indian Golden Jackal', 'filename': 'CSIMG_3463_IndianGoldenJackal.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13470', 'caption': 'Indian Golden Jackal', 'filename': 'CSIMG_3470_IndianGoldenJackal.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13484', 'caption': 'Nilgai', 'filename': 'CSIMG_3484_Neelgai_.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13564', 'caption': 'Tiger (Laxmi)', 'filename': 'CSIMG_3564_Tiger_Laxmi_Pench_Turia.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13565', 'caption': 'Tiger (Laxmi)', 'filename': 'CSIMG_3565_Tiger_Laxmi_Pench_Turia.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13626', 'caption': 'Tiger (Laxmi)', 'filename': 'CSIMG_3626_Tiger_Laxmi_Pench_Turia.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13630', 'caption': 'Tiger (Laxmi)', 'filename': 'CSIMG_3630_Tiger_Laxmi_Pench_Turia.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13666', 'caption': 'Tiger (Laxmi)', 'filename': 'CSIMG_3666_Tiger_Laxmi_Pench_Turia.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13692', 'caption': 'Tiger (Laxmi)', 'filename': 'CSIMG_3692_Tiger_Laxmi_Pench_Turia.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13708', 'caption': 'Sambar Deer', 'filename': 'CSIMG_3708_SambarDeer.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS13718', 'caption': 'Sambar Deer', 'filename': 'CSIMG_3718_SambarDeer.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS14270', 'caption': 'Indian Dhole', 'filename': 'CSIMG_4270_IndianDhole.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS14521', 'caption': 'Indian Golden Jackal', 'filename': 'CSIMG_4521_IndianGoldenJackal.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS14557', 'caption': 'Indian Golden Jackal', 'filename': 'CSIMG_4557_IndianGoldenJackal.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS14651', 'caption': 'Sambar Deer', 'filename': 'CSIMG_4651_SambarDeer.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS14668', 'caption': 'Sambar Deer', 'filename': 'CSIMG_4668_SambarDeer.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS14686', 'caption': 'Sambar Deer', 'filename': 'CSIMG_4686_SambarDeer.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS15000', 'caption': 'Leopard', 'filename': 'CSIMG_5000_Leopard.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS15004', 'caption': 'Leopard', 'filename': 'CSIMG_5004_Leopard.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS15005', 'caption': 'Leopard', 'filename': 'CSIMG_5005_Leopard.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS15012', 'caption': 'Leopard', 'filename': 'CSIMG_5012_Leopard.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS15116', 'caption': 'Leopard', 'filename': 'CSIMG_5116_Leopard.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS15121', 'caption': 'Leopard', 'filename': 'CSIMG_5121_Leopard.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },
    { 'id': 'CS15283', 'caption': 'Indian Dhole', 'filename': 'CSIMG_5283_IndianDhole.jpg', 'location': 'Pench National Park', 'year': '2025', 'desc': '' },

    { 'id': '7598', 'caption': 'Sambar Deer', 'filename': '7598_SambarDeer.jpg', 'location': 'BR Hills, Karnataka', 'year': '2015', 'desc': '' },
    { 'id': '7609', 'caption': 'Wild Boar', 'filename': '7609_WildBoar.jpg', 'location': 'BR Hills, Karnataka',  'year': '2015', 'desc': '' },
    { 'id': '7714', 'caption': 'Indian Gaur', 'filename': '7714_IndianGaur.jpg', 'location': 'BR Hills, Karnataka',  'year': '2015', 'desc': '' },
    { 'id': '13019', 'caption': 'Tiger', 'filename': '13019_Tiger.jpg', 'location': 'Nagarhole Tiger Reserve, Karnataka',  'year': '2017', 'desc': '' },
    { 'id': '13019.1', 'caption': 'Tiger', 'filename': '13019_Tiger_1.jpg', 'location': 'Nagarhole Tiger Reserve, Karnataka',  'year': '2017', 'desc': '' },
    { 'id': '3999', 'caption': 'Squirrel', 'filename': '3999_Squirrel.jpg', 'location': 'Bengaluru Karnataka',  'year': '2018', 'desc': '' },
    { 'id': '14065', 'caption': 'Tiger', 'filename': '14065_Bandipur_Tiger.jpg', 'location': 'Bandipura Tiger Reserve, Karnataka',  'year': '2018', 'desc': '' },
    { 'id': '14065.1', 'caption': 'Tiger', 'filename': '14065_Bandipur_Tiger_1.jpg', 'location': 'Bandipura Tiger Reserve, Karnataka',  'year': '2018', 'desc': '' },
    { 'id': '14393', 'caption': 'Spotted Deer', 'filename': '14383_Spotted_Deer.jpg', 'location': 'Bandipura Tiger Reserve, Karnataka',  'year': '2018', 'desc': '' },
    { 'id': '143903.1', 'caption': 'Spotted Deer', 'filename': '14393_Spotted_Deer.jpg', 'location': 'Bandipura Tiger Reserve, Karnataka',  'year': '2018', 'desc': '' },
    { 'id': '14065.2', 'caption': 'Tiger', 'filename': '14065_Bandipur_Tiger_2.jpg', 'location': 'Bandipura Tiger Reserve, Karnataka',  'year': '2018', 'desc': '' },
    { 'id': '13020', 'caption': 'Tiger', 'filename': '13020_Kabini_Tiger.jpg', 'location': 'Nagarhole Tiger Reserve, Karnataka',  'year': '2017', 'desc': '' },
    { 'id': '17315', 'caption': 'Tiger', 'filename': '17315_Dommankatte_Tiger.jpg', 'location': 'Nagarhole Tiger Reserve, Karnataka',  'year': '2019', 'desc': '' },
    { 'id': '17333', 'caption': 'Tiger', 'filename': '17333_Dommankatte_Tiger.jpg', 'location': 'Nagarhole Tiger Reserve, Karnataka',  'year': '2019', 'desc': '' },
    { 'id': '17381', 'caption': 'Tiger', 'filename': '17381_Dommankatte_Tiger.jpg', 'location': 'Nagarhole Tiger Reserve, Karnataka',  'year': '2019', 'desc': '' },
    { 'id': '17363', 'caption': 'Tiger', 'filename': '17363_Dommankatte_Tiger.jpg', 'location': 'Nagarhole Tiger Reserve, Karnataka',  'year': '2019', 'desc': '' },
    { 'id': '15741', 'caption': 'Spotted Deer', 'filename': '15741_ChintalDeer.jpg', 'location': 'Nagarhole Tiger Reserve, Karnataka',  'year': '2019', 'desc': '' },
    { 'id': '15745', 'caption': 'Spotted Deer', 'filename': '15745_ChintalDeer.jpg', 'location': 'Nagarhole Tiger Reserve, Karnataka',  'year': '2019', 'desc': '' },
    { 'id': '17719', 'caption': 'Blackbuck', 'filename': '17719_Blackbuck.jpg', 'location': 'Madhugiri, Karnataka',  'year': '2020', 'desc': '' },
    { 'id': '17722', 'caption': 'Blackbuck', 'filename': '17722_Blackbuck.jpg', 'location': 'Madhugiri, Karnataka',  'year': '2020', 'desc': '' },
    { 'id': '17753', 'caption': 'Blackbuck', 'filename': '17753_Blackbuck_female.jpg', 'location': 'Madhugiri, Karnataka',  'year': '2020', 'desc': '' },
    { 'id': '17697', 'caption': 'Blackbuck', 'filename': '17697_Blackbuck.jpg', 'location': 'Madhugiri, Karnataka',  'year': '2020', 'desc': '' },
    { 'id': '17952', 'caption': 'Blackbuck', 'filename': '17952_Blackbuck.jpg', 'location': 'Madhugiri, Karnataka',  'year': '2020', 'desc': '' },
    { 'id': '17729', 'caption': 'Blackbuck', 'filename': '17729_Blackbuck_Goat.jpg', 'location': 'Madhugiri, Karnataka',  'year': '2020', 'desc': '' },
    { 'id': '17751', 'caption': 'Blackbuck', 'filename': '17751_Blackbuck_female.jpg', 'location': 'Madhugiri, Karnataka',  'year': '2020', 'desc': '' },
    { 'id': '19021', 'caption': 'Malabar Giant Squirrel', 'filename': '19021_MalabarGaintSquirrel.jpg', 'location': 'BR Hills, Karnataka',  'year': '2021', 'desc': '' },
    { 'id': '18990', 'caption': 'Sloth Bear', 'filename': '18990_SlothBear_KGudi.jpg', 'location': 'BR Hills, Karnataka',  'year': '2021', 'desc': '' },
    { 'id': '19030', 'caption': 'Malabar Giant Squirrel', 'filename': '19030_MalabarGaintSquirrel.jpg' , 'location': 'BR Hills, Karnataka',  'year': '2021', 'desc': '' },
    { 'id': 'C7346', 'caption': 'Barking Deer', 'filename': 'C7346_Barking_Deer.png' , 'location': 'BR Hills, Karnataka',  'year': '2024', 'desc': '' },
    { 'id': 'C7815', 'caption': 'Barking Deer', 'filename': 'C7815_Barking_Deer.png' , 'location': 'BR Hills, Karnataka',  'year': '2024', 'desc': '' }
];

